import {evaluateTool} from '@agent/security';
import type {Evidence,Plan,RunState} from '@agent/contracts';
export function createPlan(request:string,repository:string):Plan { return {summary:`فحص ${repository}: ${request}`,steps:['قراءة بنية المستودع','تحليل سبب المشكلة','اقتراح التغيير','تشغيل الاختبارات','إعداد Evidence'],tools:[{name:'repo.get',input:{repository}},{name:'file.read',input:{repository}},{name:'test.run',input:{repository}}]};}
export function nextState(state:RunState,approval=false):RunState { if(state==='PLANNED') return 'RUNNING'; if(state==='RUNNING') return 'WAITING_APPROVAL'; if(state==='WAITING_APPROVAL') return approval?'EXECUTING':'CANCELLED'; if(state==='EXECUTING') return 'VERIFYING'; if(state==='VERIFYING') return 'COMPLETED'; return state; }
export function policySummary(plan:Plan){return plan.tools.map(t=>({tool:t.name,...evaluateTool(t)}));}
export function evidence(runId:string,request:string,plan:Plan,state:RunState):Evidence{return {runId,request,plan:plan.steps,tools:plan.tools.map(t=>t.name),filesChanged:[],commands:[],tests:[],gitDiff:'',result:state==='COMPLETED'?'SUCCESS':'PENDING'};}

import type {IPlugin} from '@agent/contracts';
import {TaskRegistry,StrategyRegistry,initializePlugins} from '@agent/extension-system'; import {ApprovalGateway} from './approval-gateway.js'; import type {ApprovalStore} from '@agent/approval-store';
export async function initAgent(options:{plugins?:IPlugin[];policiesDir?:string;approvalStore?:ApprovalStore}={}){const taskRegistry=new TaskRegistry();const strategyRegistry=new StrategyRegistry();const policiesDir=options.policiesDir||'./policies/approval/';const policies=options.plugins?(await initializePlugins(options.plugins,taskRegistry,strategyRegistry,policiesDir)).policies:{};const approvalGateway=new ApprovalGateway(undefined,policiesDir,options.approvalStore);const executeTask=async(taskId:string,input:unknown)=>{const task=taskRegistry.get(taskId);if(!task)throw new Error(`Task ${taskId} not found`);const parsed=task.schema.safeParse(input);if(!parsed.success)throw new Error(`Invalid input for task ${taskId}`);let level=(task.approvalPolicy?.level||task.requiredApprovalLevel||1) as 1|2|3;if(task.approvalPolicy?.overrideLevel)level=await task.approvalPolicy.overrideLevel(parsed.data);const approval=await approvalGateway.request(level,parsed.data as Record<string,unknown>);if(!approval.approved)throw new Error(`Approval denied: ${approval.reason}`);return task.handler(parsed.data,{agentId:'gethip-agent',traceId:crypto.randomUUID(),approvalGateway});};return {taskRegistry,strategyRegistry,policies,approvalGateway,executeTask};}
